# Generated by Django 5.1.4 on 2024-12-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispapp", "0003_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=100)),
            ],
        ),
    ]
