# Generated by Django 5.1.4 on 2024-12-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispapp", "0004_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="period",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="wispapp.period",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="distribution_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wispapp.distribution_type",
            ),
        ),
    ]
