# Generated by Django 5.1.4 on 2024-12-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispapp", "0005_movement_period_alter_category_distribution_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salary",
            name="date",
        ),
        migrations.AddField(
            model_name="salary",
            name="period",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="wispapp.period",
            ),
        ),
    ]
