# Generated by Django 5.1.4 on 2025-05-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispapp", "0007_member_user_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_household",
                to="wispapp.household",
            ),
        ),
    ]
