# Generated by Django 5.1.4 on 2025-05-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wispapp", "0011_movementdistribution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movementdistribution",
            name="updated_at",
        ),
    ]
